spring:
  application:
   name: "file-flat-converter"


application:
  directories:
    input: "C:/Proyectos/file-flat-converter/input"
    output: "C:/Proyectos/file-flat-converter/output"
    fail: "C:/Proyectos/file-flat-converter/fail"
